---
neovim_packages:
  - gcc
  - make
  - git
  - ripgrep
  - fd
  - tree-sitter-cli
  - unzip
  - neovim
  - xclip

neovim_packages_apt:
  - gcc
  - make
  - git
  - ripgrep
  - fd-find
  - unzip
  - neovim
