---
- name: Install tldr
  ansible.builtin.include_tasks:
    file: "install-{{ 'debian' if ansible_os_family == 'Debian' else 'arch' }}.yml"

- name: Update tldr cache
  ansible.builtin.command:
    cmd: tldr --update
    creates: "{{ user_home }}/.local/share/tldr"
