---
- name: Install Node.js packages
  become: true
  community.general.pacman:
    name: "{{ npm_packages }}"
    state: present

- name: Configure npm global directory
  ansible.builtin.command:
    cmd: npm config set prefix '{{ user_home }}/.npm-global'
  changed_when: false

- name: Ensure npm global directory exists
  ansible.builtin.file:
    path: "{{ user_home }}/.npm-global/bin"
    state: directory
    mode: "0755"

