---
nvidia_driver_package: nvidia-open
nvidia_packages:
  - nvidia-open
  - nvidia-utils
  - lib32-nvidia-utils
  - opencl-nvidia
  - libva-nvidia-driver
  - nvidia-settings
  - egl-wayland
  - vulkan-icd-loader

nvidia_kernel_modules:
  - nvidia
  - nvidia_modeset
  - nvidia_uvm
  - nvidia_drm

nvidia_modprobe_options:
  - "options nvidia_drm modeset=1"
  - "options nvidia NVreg_TemporaryFilePath=/var/tmp"

nvidia_services:
  - nvidia-suspend.service
  - nvidia-hibernate.service
  - nvidia-resume.service

nvidia_power_management: true
