---
- name: Skip on WSL
  ansible.builtin.meta: end_role
  when: ansible_host_environment_is_wsl | default(false) | bool

- name: Install audio packages
  become: true
  community.general.pacman:
    name: "{{ audio_packages }}"
    state: present
