---
- name: Install kitty
  become: true
  community.general.pacman:
    name: "{{ kitty_packages }}"
    state: present

- name: Ensure kitty config directory exists
  ansible.builtin.file:
    path: "{{ user_home }}/.config/kitty"
    state: directory
    mode: "0755"

- name: Deploy kitty config
  ansible.builtin.template:
    src: kitty.conf.j2
    dest: "{{ user_home }}/.config/kitty/kitty.conf"
    mode: "0644"
