---
- name: Install git packages
  become: true
  ansible.builtin.apt:
    name: "{{ git_packages_apt }}"
    state: present

- name: Get latest delta version
  ansible.builtin.uri:
    url: https://api.github.com/repos/dandavison/delta/releases/latest
    return_content: true
  register: delta_release
  check_mode: false

- name: Install delta from deb package
  become: true
  ansible.builtin.apt:
    deb: "https://github.com/dandavison/delta/releases/download/{{ delta_release.json.tag_name }}/git-delta_{{ delta_release.json.tag_name | regex_replace('^v', '') }}_amd64.deb"
