---
- name: Detect 1Password
  ansible.builtin.command:
    cmd: which op
  changed_when: false
  failed_when: false
  check_mode: false
  register: op_check

- name: Check 1Password has accounts configured
  ansible.builtin.shell: op account list 2>/dev/null | grep -q .
  changed_when: false
  failed_when: false
  check_mode: false
  register: op_account_check
  when: op_check.rc == 0

- name: Register 1Password
  ansible.builtin.set_fact:
    op_installed: "{{ op_check.rc == 0 and (op_account_check.rc | default(1)) == 0 }}"
