---
- name: Install git-credential-manager (AUR)
  kewlfft.aur.aur:
    name: git-credential-manager
    use: yay
    state: present
  become: "{{ ansible_facts['user_id'] == 'root' }}"
  become_user: "{{ host_user }}"

- name: Install skia-sharp (GCM UI dependency)
  become: true
  community.general.pacman:
    name: skia-sharp
    state: present

- name: Configure GCM credential store
  community.general.git_config:
    name: credential.credentialStore
    file: "{{ user_home }}/.config/git/config"
    scope: file
    value: secretservice

- name: Configure GCM helper path
  community.general.git_config:
    name: credential.helper
    file: "{{ user_home }}/.config/git/config"
    scope: file
    value: /usr/bin/git-credential-manager

- name: Disable GCM GUI prompts (use browser OAuth directly)
  community.general.git_config:
    name: credential.guiPrompt
    file: "{{ user_home }}/.config/git/config"
    scope: file
    value: "false"
