---
- name: Install neovim packages
  become: true
  community.general.pacman:
    name: "{{ neovim_packages }}"
    state: present

- name: Ensure neovim config directory exists
  ansible.builtin.file:
    path: "{{ user_home }}/.config/nvim"
    state: directory
    mode: "0755"

- name: Clone kickstart.nvim
  ansible.builtin.git:
    repo: https://github.com/nvim-lua/kickstart.nvim.git
    dest: "{{ user_home }}/.config/nvim"
    version: master
    update: false

- name: Enable custom plugins loading
  ansible.builtin.lineinfile:
    path: "{{ user_home }}/.config/nvim/init.lua"
    regexp: '^\s*[-]*\s*require .custom\.plugins.'
    line: "  require 'custom.plugins'"

- name: Deploy custom neovim plugins
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ user_home }}/.config/nvim/lua/custom/plugins/{{ item }}"
    mode: "0644"
  loop:
    - harpoon.lua
    - codecompanion.lua
    - remap.lua
