---
- name: Skip on WSL
  ansible.builtin.meta: end_role
  when: ansible_host_environment_is_wsl | default(false) | bool

- name: Install Nerd Fonts
  become: true
  community.general.pacman:
    name: "{{ fonts_nerd_fonts }}"
    state: present

- name: Install extra fonts
  become: true
  community.general.pacman:
    name: "{{ fonts_extra }}"
    state: present

- name: Refresh font cache
  ansible.builtin.command:
    cmd: fc-cache -fv
  changed_when: false
